services:
  mongodb:
    image: mongo
    container_name: article-mongo-database-container
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db
      - mongodbconfig:/data/configdb
    restart: unless-stopped

  redis:
    image: redis
    container_name: redis-server-container
    volumes:
      - redis-data:/data
    network_mode: "service:mongodb"
    restart: unless-stopped

  celery:
    build:
      context: .
      dockerfile: celery-scheduler/Dockerfile-celery  # Path to your Dockerfile
    image: celery-image
    container_name: celery-container
    working_dir: /app
    command: celery -A celery-scheduler.tasks worker --beat --concurrency=1 --pool=solo
    env_file:
      - .env
    depends_on:
      - api
    network_mode: "service:mongodb"
    restart: unless-stopped

  api:
    build:
      context: .
      args:
        HOST: ${HOST}
        PORT: ${PORT}
    image: db-handler-fastapi-image
    container_name: db-handler-fastapi-container
    env_file:
      - .env
    depends_on:
      - mongodb
      - redis
    network_mode: "service:mongodb"
    restart: unless-stopped

volumes:
  mongodbdata:
  mongodbconfig:
  redis-data:
