# Use the official Python image as the base image
FROM python:3.9-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the requirements file into the container
COPY ../globals.py /app/

# Install dependencies
RUN pip install --no-cache-dir celery requests python-dotenv redis

# Copy the requirements file into the container
COPY  celery-scheduler  /app/celery-scheduler
